package expose

import (
	"encoding/json"
	"fmt"
	"strconv"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/apimachinery/pkg/util/strategicpatch"
)

// buildDryRunAuthSecret returns a Secret manifest with a placeholder value so
// that dry-run output is complete. The real secret is randomly generated and
// stored at actual deploy time.
func (c *Config) buildDryRunAuthSecret() *corev1.Secret {
	return &corev1.Secret{
		TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "Secret"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      c.AuthSecretName(),
			Namespace: c.Namespace,
			Labels:    c.commonLabels(),
		},
		StringData: map[string]string{
			authSecretDataKey: "<auto-generated at deploy time>",
		},
	}
}

func (c *Config) buildServiceAccount() *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "ServiceAccount"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      c.ResourceName(),
			Namespace: c.Namespace,
			Labels:    c.commonLabels(),
		},
	}
}

func (c *Config) buildRole() *rbacv1.Role {
	return &rbacv1.Role{
		TypeMeta: metav1.TypeMeta{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "Role"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      c.ResourceName(),
			Namespace: c.Namespace,
			Labels:    c.commonLabels(),
		},
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{""},
				Resources: []string{"services"},
				Verbs:     []string{"get", "list", "watch", "create", "update", "patch", "delete"},
			},
		},
	}
}

func (c *Config) buildRoleBinding() *rbacv1.RoleBinding {
	return &rbacv1.RoleBinding{
		TypeMeta: metav1.TypeMeta{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "RoleBinding"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      c.ResourceName(),
			Namespace: c.Namespace,
			Labels:    c.commonLabels(),
		},
		Subjects: []rbacv1.Subject{
			{Kind: "ServiceAccount", Name: c.ResourceName(), Namespace: c.Namespace},
		},
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     c.ResourceName(),
		},
	}
}

func (c *Config) buildDeployment() (*appsv1.Deployment, error) {
	replicas := int32(1)
	serverPort := int32(c.ServerPort)

	d := &appsv1.Deployment{
		TypeMeta: metav1.TypeMeta{APIVersion: "apps/v1", Kind: "Deployment"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      c.ResourceName(),
			Namespace: c.Namespace,
			Labels:    c.commonLabels(),
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app.kubernetes.io/name": c.ResourceName(),
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: c.commonLabels()},
				Spec: corev1.PodSpec{
					ServiceAccountName: c.ResourceName(),
					Containers: []corev1.Container{
						{
							Name:  "server",
							Image: c.Image,
							Args:  []string{"server"},
							Env: []corev1.EnvVar{
								{Name: "BURROW_JWT_ALG", Value: "HS256"},
								{
									Name: "BURROW_JWT_HMAC_SECRET",
									ValueFrom: &corev1.EnvVarSource{
										SecretKeyRef: &corev1.SecretKeySelector{
											LocalObjectReference: corev1.LocalObjectReference{Name: c.AuthSecretName()},
											Key:                  authSecretDataKey,
										},
									},
								},
								{Name: "BURROW_JWT_AUDIENCE", Value: jwtAudience},
								{Name: "BURROW_JWT_ISSUER", Value: jwtIssuer},
								{Name: "BURROW_SERVER_ADDR", Value: ":" + strconv.Itoa(c.ServerPort)},
							// BURROW_BRIDGE_HOST sets the bind host; each client gets a random port.
							{Name: "BURROW_BRIDGE_HOST", Value: "0.0.0.0"},
								{
									Name: "BURROW_NAMESPACE",
									ValueFrom: &corev1.EnvVarSource{
										FieldRef: &corev1.ObjectFieldSelector{FieldPath: "metadata.namespace"},
									},
								},
								{Name: "BURROW_ENABLE_KUBE_API", Value: "true"},
							},
							Ports: []corev1.ContainerPort{
								{Name: "http", ContainerPort: serverPort, Protocol: corev1.ProtocolTCP},
							},
							ReadinessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path: "/healthz",
										Port: intstr.FromInt32(serverPort),
									},
								},
								InitialDelaySeconds: 2,
								PeriodSeconds:       5,
							},
							LivenessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path: "/healthz",
										Port: intstr.FromInt32(serverPort),
									},
								},
								InitialDelaySeconds: 5,
								PeriodSeconds:       15,
							},
						},
					},
				},
			},
		},
	}

	return applyPatch(d, c.PatchDeployment, appsv1.Deployment{})
}

func (c *Config) buildService() (*corev1.Service, error) {
	svcType := corev1.ServiceTypeClusterIP
	if !c.IngressMode() {
		svcType = corev1.ServiceTypeLoadBalancer
	}

	svc := &corev1.Service{
		TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "Service"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      c.ResourceName(),
			Namespace: c.Namespace,
			Labels:    c.commonLabels(),
		},
		Spec: corev1.ServiceSpec{
			Type: svcType,
			Selector: map[string]string{
				"app.kubernetes.io/name": c.ResourceName(),
			},
			Ports: []corev1.ServicePort{
				{
					Name:       "http",
					Port:       int32(c.ServerPort),
					TargetPort: intstr.FromString("http"),
					Protocol:   corev1.ProtocolTCP,
				},
			},
		},
	}

	return applyPatch(svc, c.PatchService, corev1.Service{})
}

func (c *Config) buildIngress() (*networkingv1.Ingress, error) {
	if !c.IngressMode() {
		return nil, nil
	}

	pathType := networkingv1.PathTypePrefix

	// Start with default WebSocket-friendly annotations; user annotations override.
	annotations := map[string]string{
		"nginx.ingress.kubernetes.io/proxy-read-timeout": "3600",
		"nginx.ingress.kubernetes.io/proxy-send-timeout": "3600",
		"nginx.ingress.kubernetes.io/proxy-http-version": "1.1",
	}
	for k, v := range c.IngressAnnotations {
		annotations[k] = v
	}

	ing := &networkingv1.Ingress{
		TypeMeta: metav1.TypeMeta{APIVersion: "networking.k8s.io/v1", Kind: "Ingress"},
		ObjectMeta: metav1.ObjectMeta{
			Name:        c.ResourceName(),
			Namespace:   c.Namespace,
			Labels:      c.commonLabels(),
			Annotations: annotations,
		},
		Spec: networkingv1.IngressSpec{
			Rules: []networkingv1.IngressRule{
				{
					Host: c.Hostname,
					IngressRuleValue: networkingv1.IngressRuleValue{
						HTTP: &networkingv1.HTTPIngressRuleValue{
							Paths: []networkingv1.HTTPIngressPath{
								{
									Path:     "/",
									PathType: &pathType,
									Backend: networkingv1.IngressBackend{
										Service: &networkingv1.IngressServiceBackend{
											Name: c.ResourceName(),
											Port: networkingv1.ServiceBackendPort{Name: "http"},
										},
									},
								},
							},
						},
					},
				},
			},
			// TLS is always enabled for Ingress mode. secretName is optional —
			// omitting it lets the ingress controller use its default certificate.
			TLS: func() []networkingv1.IngressTLS {
				tls := networkingv1.IngressTLS{Hosts: []string{c.Hostname}}
				if c.TLSSecret != "" {
					tls.SecretName = c.TLSSecret
				}
				return []networkingv1.IngressTLS{tls}
			}(),
		},
	}

	if c.IngressClass != "" {
		ing.Spec.IngressClassName = &c.IngressClass
	}

	return applyPatch(ing, c.PatchIngress, networkingv1.Ingress{})
}

// applyPatch applies a strategic merge patch (JSON string) to obj, returning
// a new instance of the same type. dataStruct is passed to the strategic merge
// patcher so it can read the patchStrategy struct tags (e.g. for Deployment
// containers array merging).
func applyPatch[T any](obj *T, patch string, dataStruct T) (*T, error) {
	if patch == "" {
		return obj, nil
	}
	base, err := json.Marshal(obj)
	if err != nil {
		return nil, fmt.Errorf("marshaling resource for patch: %w", err)
	}
	patched, err := strategicpatch.StrategicMergePatch(base, []byte(patch), dataStruct)
	if err != nil {
		return nil, fmt.Errorf("applying strategic merge patch: %w", err)
	}
	var result T
	if err := json.Unmarshal(patched, &result); err != nil {
		return nil, fmt.Errorf("unmarshaling patched resource: %w", err)
	}
	return &result, nil
}
