BINARY := burrow
VERSION ?= dev
JWT_ALG ?= RS256
JWT_HMAC_SECRET ?= dev-secret
JWT_PUBLIC_KEY_FILE ?=
JWKS_URL ?=
JWKS_REFRESH ?= 5m
JWT_ISSUER ?= dev-local
JWT_AUDIENCE ?= burrow-server
BEARER_TOKEN ?=
BEARER_TOKEN_FILE ?=
TOKEN_REFRESH_WINDOW ?= 30s
CLIENT_RETRY_INTERVAL ?= 1s
CLIENT_AUTH_RETRY_INTERVAL ?= 5s
SERVER_ADDR ?= :8080
BRIDGE_HOST ?= 0.0.0.0
SERVER_URL ?= ws://127.0.0.1:8080/ws
CLIENT_ID ?= client-a
LOCAL_TARGET ?= 127.0.0.1:3000

.PHONY: build test e2e-smoke run-server run-client run-server-jwt-dev run-client-jwt-dev tidy

build:
	go build -ldflags "-s -w -X github.com/splattner/burrow/internal/version.Version=$(VERSION)" -o bin/$(BINARY) ./cmd/root

test:
	go test ./...

e2e-smoke:
	bash ./test/e2e/smoke.sh

run-server:
	BURROW_JWT_ALG=$(JWT_ALG) \
	BURROW_JWT_HMAC_SECRET=$(JWT_HMAC_SECRET) \
	BURROW_JWT_PUBLIC_KEY_FILE=$(JWT_PUBLIC_KEY_FILE) \
	BURROW_JWKS_URL=$(JWKS_URL) \
	BURROW_JWKS_REFRESH=$(JWKS_REFRESH) \
	BURROW_JWT_ISSUER=$(JWT_ISSUER) \
	BURROW_JWT_AUDIENCE=$(JWT_AUDIENCE) \
	BURROW_SERVER_ADDR=$(SERVER_ADDR) \
	BURROW_BRIDGE_HOST=$(BRIDGE_HOST) \
	go run ./cmd/root server

run-server-jwt-dev:
	BURROW_JWT_ALG=HS256 \
	BURROW_JWT_HMAC_SECRET=$(JWT_HMAC_SECRET) \
	BURROW_JWT_ISSUER=$(JWT_ISSUER) \
	BURROW_JWT_AUDIENCE=$(JWT_AUDIENCE) \
	BURROW_SERVER_ADDR=$(SERVER_ADDR) \
	BURROW_BRIDGE_HOST=$(BRIDGE_HOST) \
	go run ./cmd/root server

run-client:
	BURROW_BEARER_TOKEN=$(BEARER_TOKEN) \
	BURROW_BEARER_TOKEN_FILE=$(BEARER_TOKEN_FILE) \
	BURROW_TOKEN_REFRESH_WINDOW=$(TOKEN_REFRESH_WINDOW) \
	BURROW_CLIENT_RETRY_INTERVAL=$(CLIENT_RETRY_INTERVAL) \
	BURROW_CLIENT_AUTH_RETRY_INTERVAL=$(CLIENT_AUTH_RETRY_INTERVAL) \
	BURROW_SERVER_URL=$(SERVER_URL) \
	BURROW_CLIENT_ID=$(CLIENT_ID) \
	BURROW_LOCAL_TARGET=$(LOCAL_TARGET) \
	go run ./cmd/root client

run-client-jwt-dev:
	CLIENT_ID=$(CLIENT_ID) \
	LOCAL_TARGET=$(LOCAL_TARGET) \
	SERVER_URL=$(SERVER_URL) \
	JWT_AUDIENCE=$(JWT_AUDIENCE) \
	JWT_ISSUER=$(JWT_ISSUER) \
	JWT_HMAC_SECRET=$(JWT_HMAC_SECRET) \
	bash ./scripts/run-client-jwt-dev.sh

tidy:
	go mod tidy
