BINARY := k8s-reverse-tunnel
JWT_ALG ?= RS256
JWT_HMAC_SECRET ?= dev-secret
JWT_PUBLIC_KEY_FILE ?=
JWKS_URL ?=
JWKS_REFRESH ?= 5m
JWT_ISSUER ?= dev-local
JWT_AUDIENCE ?= krt-server
BEARER_TOKEN ?=
BEARER_TOKEN_FILE ?=
TOKEN_REFRESH_WINDOW ?= 30s
CLIENT_RETRY_INTERVAL ?= 1s
CLIENT_AUTH_RETRY_INTERVAL ?= 5s
SERVER_ADDR ?= :8080
BRIDGE_ADDR ?= :1111
SERVER_URL ?= ws://127.0.0.1:8080/ws
CLIENT_ID ?= client-a
LOCAL_TARGET ?= 127.0.0.1:3000

.PHONY: build test e2e-smoke run-server run-client run-server-jwt-dev run-client-jwt-dev tidy

build:
	go build -o bin/$(BINARY) ./cmd/root

test:
	go test ./...

e2e-smoke:
	bash ./test/e2e/smoke.sh

run-server:
	KRT_JWT_ALG=$(JWT_ALG) \
	KRT_JWT_HMAC_SECRET=$(JWT_HMAC_SECRET) \
	KRT_JWT_PUBLIC_KEY_FILE=$(JWT_PUBLIC_KEY_FILE) \
	KRT_JWKS_URL=$(JWKS_URL) \
	KRT_JWKS_REFRESH=$(JWKS_REFRESH) \
	KRT_JWT_ISSUER=$(JWT_ISSUER) \
	KRT_JWT_AUDIENCE=$(JWT_AUDIENCE) \
	KRT_SERVER_ADDR=$(SERVER_ADDR) \
	KRT_BRIDGE_ADDR=$(BRIDGE_ADDR) \
	go run ./cmd/root server

run-server-jwt-dev:
	KRT_JWT_ALG=HS256 \
	KRT_JWT_HMAC_SECRET=$(JWT_HMAC_SECRET) \
	KRT_JWT_ISSUER=$(JWT_ISSUER) \
	KRT_JWT_AUDIENCE=$(JWT_AUDIENCE) \
	KRT_SERVER_ADDR=$(SERVER_ADDR) \
	KRT_BRIDGE_ADDR=$(BRIDGE_ADDR) \
	go run ./cmd/root server

run-client:
	KRT_BEARER_TOKEN=$(BEARER_TOKEN) \
	KRT_BEARER_TOKEN_FILE=$(BEARER_TOKEN_FILE) \
	KRT_TOKEN_REFRESH_WINDOW=$(TOKEN_REFRESH_WINDOW) \
	KRT_CLIENT_RETRY_INTERVAL=$(CLIENT_RETRY_INTERVAL) \
	KRT_CLIENT_AUTH_RETRY_INTERVAL=$(CLIENT_AUTH_RETRY_INTERVAL) \
	KRT_SERVER_URL=$(SERVER_URL) \
	KRT_CLIENT_ID=$(CLIENT_ID) \
	KRT_LOCAL_TARGET=$(LOCAL_TARGET) \
	go run ./cmd/root client

run-client-jwt-dev:
	CLIENT_ID=$(CLIENT_ID) \
	LOCAL_TARGET=$(LOCAL_TARGET) \
	SERVER_URL=$(SERVER_URL) \
	JWT_AUDIENCE=$(JWT_AUDIENCE) \
	JWT_ISSUER=$(JWT_ISSUER) \
	JWT_HMAC_SECRET=$(JWT_HMAC_SECRET) \
	bash ./scripts/run-client-jwt-dev.sh

tidy:
	go mod tidy
